name: Get Changed GHA Items From File List
description: >
  Get PowerShell array of GitHub Action item names derived from list of changed file names.

inputs:
  file-include-list:
    required: false
    default: '@()'
    description: >
      PowerShell string array of file names to return corresponding GitHub Actions (GHA) items. The
      parameter must be a PowerShell string array.
outputs:
  changed-items:
    description: A PowerShell array of GHA item names related to included file list input.
    value: ${{ steps.get-gha-items.outputs.changed-items }}
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Get GHA Items
      id: get-gha-items
      shell: pwsh
      run: |
        $params = @{
            FileIncludeList = ${{ inputs.file-include-list }}
        }
        Get-GhaItemsFromFileList @params
