name: Set up SQL Server
description: Sets up SQL Server with Lombiq-recommended defaults.

runs:
  using: composite
  steps:
    - name: Setup
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Set up SQL Server
      shell: pwsh
      run: Initialize-SqlServer

    # Needs to be a separate step, otherwise the Chocolatey installation won't be visible.
    - name: Wait for SQL Server to start
      shell: pwsh
      run: Wait-SqlServer
