name: Free up Space
description: >
  Frees up storage space on the runner by deleting files unnecessary for .NET projects.

runs:
  using: composite
  steps:
    - name: Free up Space Ubuntu
      shell: pwsh
      if: runner.os == 'Linux'
      run: |
        # Removes the local cache of downloaded packages but doesn't remove installed software.
        sudo apt-get clean

        # Remove Android SDK, which is huge, typically 8-12 GB.
        sudo rm -rf /usr/local/lib/android

    - name: Free up Space Windows
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        # Removes superseded Windows component store files.
        Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

        # Remove Android SDK, which is huge, typically 8-12 GB.
        if ($Env:ANDROID_HOME)
        {
            Remove-Item -Path "$Env:ANDROID_HOME" -Recurse -Force -ErrorAction SilentlyContinue
        }

        $extraAndroidPaths = @(
            "$Env:LOCALAPPDATA\Android",
            "C:\Android"
        )

        foreach ($path in $extraAndroidPaths)
        {
            if (Test-Path $path)
            {
                Remove-Item $path -Recurse -Force -ErrorAction SilentlyContinue
            }
        }

        # Remove other large caches and temp files.
        Remove-Item -Path "$Env:TEMP\*" -Recurse -Force -ErrorAction SilentlyContinue

