name: Install sqlcmd
description: Installs the SQL Server command-line tools (https://aka.ms/sqlpackage).

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Check if sqlcmd is installed
      id: check-sqlcmd
      shell: pwsh
      run: |
        Set-GitHubOutput 'available' ($null -ne (Get-Command sqlcmd -ErrorAction SilentlyContinue))

    - name: Install a SQL Server suite of tools
      uses: shaybentk/mssqlsuite@192fce1fb38a4164d22ed8dba86d8199bb158d0e # v0.0.4
      if: steps.check-sqlcmd.outputs.available != 'true'
      with:
        install: sqlpackage

    - name: Display sqlcmd version
      shell: pwsh
      run: sqlcmd -?
