name: Install sqlcmd
description: Installs the SQL Server command-line tools (https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility).

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Check if sqlcmd is installed
      id: check-sqlcmd
      shell: pwsh
      run: |
        Set-GitHubOutput 'available' ($null -ne (Get-Command sqlcmd -ErrorAction SilentlyContinue))

    # Source: https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=go%2Clinux&pivots=cs1-bash#download-and-install-sqlcmd
    - name: Install sqlcmd on Linux
      if: runner.os == 'Linux' && steps.check-sqlcmd.outputs.available != 'true'
      shell: bash
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
        sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/22.04/prod.list)" -y
        sudo apt-get update
        sudo apt-get install sqlcmd

    - name: Display sqlcmd version
      shell: pwsh
      run: sqlcmd -?
