name: Update Github Issue and Pull Request
description: |
  Prefixes the PR title with a Jira issue key, adds the Jira key and the issue key to the body if not present, and also
  assigns the issue to the PR author.

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Add Jira Issue Code to Pull Request
      shell: pwsh
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      run: |
        $params = @{
            JiraBaseUrl = $Env:JIRA_BASE_URL ? $Env:JIRA_BASE_URL : "https://lombiq.atlassian.net"
            GitHubRepository = $Env:GITHUB_REPOSITORY
            Branch = $Env:GITHUB_HEAD_REF
            Title = $Env:PR_TITLE
            Body = $Env:PR_BODY
            Assignee = "${{ env.PR_AUTHOR }}"
            PullRequestID = ${{ github.event.number }}
        }
        Update-GitHubIssueAndPullRequest @params
