# This file needs to be present in this exact folder for the workflow using this action to be able to work with submodules.
name: Spelling
description: Checks for spelling errors in files.

inputs:
  # When updating check-spelling to a new version, check the release notes or the "dictionary-source-prefixes" parameter
  # of "action.yaml" according to the commit of the release to find out the dictionary version tag and update the
  # default value here and in the spelling workflow.
  dictionary-source-prefixes:
    description: >
      JSON map of prefixes for dictionary URLs, "cspell" is necessary. See
      https://github.com/check-spelling/check-spelling/blob/v0.0.21/action.yml#L67 for current version.
    required: false
    default: >
      {
        "cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220816/dictionaries/"
      }
  extra-dictionaries:
    description: Space delimited list of URLs (or `prefix:`+path) to additional word lists
    required: false
    default: |
      cspell:aws/aws.txt
      cspell:csharp/csharp.txt
      cspell:css/css.txt
      cspell:django/django.txt
      cspell:dotnet/dotnet.txt
      cspell:filetypes/filetypes.txt
      cspell:html/html.txt
      cspell:npm/npm.txt
      cspell:rust/rust.txt
      cspell:scala/scala.txt
      cspell:software-terms/src/software-terms.txt
      cspell:typescript/typescript.txt
  config:
    description: Spelling configuration directory
    required: false
    default: .github/actions/check-spelling
  spell-check-this:
    description: Repository with default configuration to use, the default from Check Spelling is ''.
    required: false
    default: Lombiq/GitHub-Actions@dev

runs:
  using: "composite"
  steps:
    - name: Check Spelling
      uses: check-spelling/check-spelling@v0.0.21
      with:
        config: ${{ inputs.config }}
        dictionary_source_prefixes: ${{ inputs.dictionary-source-prefixes }}
        experimental_apply_changes_via_bot: 0
        extra_dictionaries: ${{ inputs.extra-dictionaries }}
        post_comment: 1
        spell_check_this: ${{ inputs.spell-check-this }}
        suppress_push_for_open_pull_request: 1
