name: Mirror branch
description: Mirrors branches from a repository to another.

inputs:
  source-repository:
    description: >
      The repository's path, e.g. 'Lombiq/GitHub-Actions', to mirror branches from. Override this parameter if it
      differs from the repository running the workflow, or when you wish to check out a repository different from the
      current one.
    default: ${{ github.repository }}
  source-token:
    description: >
      Optional PAT to fetch the source repository's branches from the GitHub API and for checkout. Not needed when the
      'branch-names' parameter is used while the source repository is public.
  checkout:
    description: >
      Set to 'false' if the source repository is already checked out with history (not shallow clone). Leaving it on the
      default value ('true') makes the 'source-repository' parameter required.
    default: 'true'
  destination-repository:
    description: The destination repository path, e.g. 'Lombiq/GitHub-Actions'.
    required: true
  destination-token:
    description: >
      Required PAT to fetch the destination repository's branches and to push to it.
    required: true
  branch-names:
    description: >
      A comma-separated list of branch names to push to the destination repository. Use this parameter when the
      names of the branches that are outdated on the destination are known, e.g. 'github.ref' when the workflow is
      triggered by the push event in the source repository. This parameter takes precedence over 'branch-names' when not
      empty.
  branch-regex:
    description: >
      A regex to match the branches of the source repository. Matching branches' head commit hashes will be compared
      between the source and destination repository using the GitHub API to prevent unnecessary push operations. Default
      value matches any branch.
    default: '.+'

runs:
  using: composite
  steps:
    - name: Parameter validation
      shell: pwsh
      run: |
        $branchNames = '${{ inputs.branch-names }}'.Trim()
        $branchRegex = '${{ inputs.branch-regex }}'.Trim()
        $sourceRepository = '${{ inputs.source-repository }}'
        $destinationRepository = '${{ inputs.destination-repository }}'
        $checkout = '${{ inputs.checkout }}' -eq 'true'

        if (-not $branchNames -and -not $branchRegex)
        {
          throw 'At least one of the ''branch-names'' and ''branch-regex'' parameters must be non-empty.'
        }

        if (-not $branchNames -and -not $sourceRepository -match '^[^/]+/[^/]+$')
        {
          throw 'The ''branch-regex'' parameter used, so the source repository path must be provided too.'
        }

        if ($checkout -and -not $sourceRepository -match '^[^/]+/[^/]+$')
        {
          throw 'Checkout is enabled, so a valid source repository path must be provided too.'
        }

        if ($sourceRepository.ToLower() -eq $destinationRepository.ToLower())
        {
          throw 'The source and the destination repositories cannot be the same.'
        }

    - name: Setup Scripts
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Get source branches
      id: get-source-branches
      if: inputs.branch-names == ''
      uses: Lombiq/GitHub-Actions/.github/actions/get-branches@issue/OSOE-737
      with:
        repository: ${{ inputs.source-repository }}
        api-token: ${{ inputs.source-token }}

    - name: Get destination branches
      id: get-destination-branches
      if: inputs.branch-names == ''
      uses: Lombiq/GitHub-Actions/.github/actions/get-branches@issue/OSOE-737
      with:
        repository: ${{ inputs.destination-repository }}
        api-token: ${{ inputs.destination-token }}

    - name: Find branches to mirror
      id: find-branches
      shell: pwsh
      run: |
        $branchNames = '${{ inputs.branch-names }}'
        $branchRegex = '${{ inputs.branch-regex }}'

        if (-not $branchNames)
        {
          $sourceRepository = '${{ inputs.source-repository }}'
          $sourceBranchHashes = [System.Collections.Generic.Dictionary[string, string]]::new()

          '${{ steps.get-source-branches.outputs.branches }}' | ConvertFrom-Json |
            ForEach-Object { $sourceBranchHashes[$PSItem.name] = $PSItem.commit.sha }

          if ($sourceBranchHashes.Count -eq 0)
          {
            Write-Output "::error::Source repository '$sourceRepository' has no branches!"
            exit 1
          }

          $matchingSourceBranchNames = $sourceBranchHashes.Keys | Where-Object { $PSItem -match $branchRegex }
          if ($matchingSourceBranchNames.Count -gt 0)
          {
            Write-Output ("::notice::Found $($matchingSourceBranchNames.Count) branches in '$sourceRepository' matching '$branchRegex': " +
              ($matchingSourceBranchNames -join ', '))
          }
          else
          {
            Write-Output "::error::There are no branches in '$sourceRepository' matching '$branchRegex'!"
            exit 1
          }
          
          $destinationRepository = '${{ inputs.destination-repository }}'
          $destinationBranchHashes = [System.Collections.Generic.Dictionary[string, string]]::new()

          '${{ steps.get-destination-branches.outputs.branches }}' | ConvertFrom-Json |
            ForEach-Object { $destinationBranchHashes[$PSItem.name] = $PSItem.commit.sha }

          $mirroringBranchNames = @()
          foreach ($branch in $matchingSourceBranchNames)
          {
              if (-not $destinationBranchHashes.ContainsKey($branch) -or $sourceBranchHashes[$branch] -ne $destinationBranchHashes[$branch])
              {
                $mirroringBranchNames += $branch
              }
          }

          if ($mirroringBranchNames.Count -gt 0)
          {
            $branchNames = $mirroringBranchNames -join ', '
            Write-Output "::notice::Found $($mirroringBranchNames.Count) branches in '$destinationRepository' to be updated: $branchNames"
          }
          else
          {
            Write-Output "::notice::All the matched branches are up-to-date in '$destinationRepository'."
          }
        }

        $processedBranchNames = $branchNames -split ',' | ForEach-Object { $PSItem.Trim() } | Where-Object { $PSItem -ne '' }
        Set-GitHubOutput 'first-branch-name' $processedBranchNames[0]
        Set-GitHubOutput 'branch-names' (processedBranchNames -join ',')

    - name: Checkout source repository
      if: inputs.checkout == 'true' && steps.find-branches.outputs.first-branch-name != ''
      uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
      with:
        repository: ${{ inputs.source-repository }}
        ref: ${{ steps.find-branches.outputs.first-branch-name }}
        token: ${{ inputs.source-token }}
        fetch-depth: 0

    - name: Fetch branches and push to destination repository
      if: steps.find-branches.outputs.first-branch-name != ''
      shell: pwsh
      run: |
        $branchRefNames = [System.Collections.Generic.Dictionary[string, string]]::new()
        $branchNames = '${{ steps.find-branches.outputs.branch-names }}' -split ','
        $branchNames | ForEach-Object { $branchRefNames[$PSItem] = $PSItem -like 'refs/heads/*' ? $PSItem : "refs/heads/$PSItem" }

        # Fetching branches from the source repository. If the repository is checked out in this action, then we know
        # for sure that the first branch is already fetched, so skip that.
        $fetchRefNames = '${{ inputs.checkout }}' -eq 'true' ? $branchRefNames.Values[1..($branchRefNames.Count - 1)] : $branchRefNames.Values
        $fetchRefNames | ForEach-Object { git fetch origin "$($PSItem):$($PSItem)" }

        # Removing extra authentication header that interferes with the PAT: https://stackoverflow.com/a/69979203
        git config --unset-all http.https://github.com/.extraheader

        git remote add destination 'https://${{ inputs.destination-token }}@github.com/${{ inputs.destination-repository }}'

        foreach ($branch in $branchRefNames.Keys)
        {
          if ((git log origin/$branch..destination/$branch) -eq '')
          {
            Write-Output "$branch is already up to date."
            continue
          }

          $ref = $branchRefNames[$branch]
          git push destination "$($ref):$($ref)"
        }

    - name: Delete 'destination' remote
      if: (success() || failure()) && steps.find-branches.outputs.first-branch-name != ''
      shell: bash
      run: git remote rm destination
