name: Add/Remove Label
description: >
  Adds or removes issue and pull request labels with the GitHub CLI. Intentionally not
  documented in Actions.md since it's only meant for internal use.

inputs:
  token:
    description: github token
    required: true
    default: ''
  labels:
    description: labels to edit
    required: false
    default: ''
  label:
    description: label to edit
    required: false
    default: ''
  type:
    description: add or remove
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Add/Remove Label
      shell: pwsh
      env:
        GH_TOKEN: ${{ inputs.token }}
        LABELS: ${{ inputs.labels }}
        LABEL: ${{ inputs.label }}
        LABEL_OPERATION: ${{ inputs.type }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        & "$Env:ACTION_PATH/Update-Labels.ps1"
