name: Set up Scripts
description: >
  Adds Scripts directory at the root of this repository to the Path environment variable.

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH
