name: Enable corepack
description: >
  Enables Node corepack so any package manager can be used seamlessly. This is instead of a direct PNPM install. This
  step won't be necessary once corepack is out of the experimental state and be enabled by default, see
  https://github.com/nodejs/node/issues/50963.

runs:
  using: composite
  steps:
    - name: Enable corepack
      shell: pwsh
      run: |
        corepack enable

        # This is really only necessary to work around the https://github.com/nodejs/corepack/issues/612 corepack issue.
        # Also see https://github.com/Lombiq/NodeJs-Extensions/issues/120.
        corepack prepare pnpm@8.15.9+sha1.aa4bc353b5f59fe1f1df5d802ce049ddf7f3c60e --activate
