name: Enable corepack
description: >
  Enables Node corepack so any package manager can be used seamlessly. This is instead of a direct PNPM install.
runs:
  using: composite
  steps:
    - name: Enable corepack
      shell: pwsh
      run: |
        corepack enable
