name: Free up Space for .NET
description: >
  Frees up storage space on the runner by deleting files unnecessary for .NET projects.

runs:
  using: composite
  steps:
    - name: Free up Space Ubuntu
      shell: pwsh
      if: runner.os == 'Linux'
      run: |
        $initialSpace = (df / |
          Select-Object -Skip 1 |
          ForEach-Object { $PSItem.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)[3] } |
          Select-Object -First 1)

        # Remove the local cache of downloaded packages but don't remove installed software.
        sudo apt-get clean

        # Remove Android SDK, which is huge, typically 8-12 GB.
        sudo rm -rf /usr/local/lib/android

        # Remove all unused Docker images.
        sudo docker image prune --all --force

        # Remove unused build cache.
        sudo docker builder prune --all --force

        # Remove Java (JDKs).
        sudo rm -rf /usr/lib/jvm

        # Remove Swift toolchain.
        sudo rm -rf /usr/share/swift

        # Remove Haskell (GHC).
        sudo rm -rf /usr/local/.ghcup

        # Remove Julia.
        sudo rm -rf /usr/local/julia*

        $finalSpace = (df / |
          Select-Object -Skip 1 |
          ForEach-Object { $PSItem.Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)[3] } |
          Select-Object -First 1)
        $freedSpace = [math]::Round(($finalSpace - $initialSpace) / 1GB, 2)
        Write-Output "Freed up approximately $freedSpace GB of disk space."

    - name: Free up Space Windows
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        $initialSpace = (Get-PSDrive C).Free

        # NOT removing superseded Windows component store files, because this takes 1-2 minutes and is thus too slow.
        # Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase

        # Remove Android SDK, which is huge, typically 8-12 GB.
        if ($Env:ANDROID_HOME)
        {
            Remove-Item -Path "$Env:ANDROID_HOME" -Recurse -Force -ErrorAction SilentlyContinue
        }

        $extraAndroidPaths = @(
            "$Env:LOCALAPPDATA\Android",
            'C:\Android'
        )

        foreach ($path in $extraAndroidPaths)
        {
            if (Test-Path $path)
            {
                Remove-Item $path -Recurse -Force -ErrorAction SilentlyContinue
            }
        }

        # Remove other large caches and temp files.
        Remove-Item -Path "$Env:TEMP\*" -Recurse -Force -ErrorAction SilentlyContinue

        # Remove all unused Docker images.
        docker image prune --all --force

        # Remove unused build cache.
        docker builder prune --all --force

        # Remove Java (JDKs).
        Remove-Item -Path 'C:\hostedtoolcache\windows\Java_*' -Recurse -Force -ErrorAction SilentlyContinue

        # Remove Swift toolchain.
        Remove-Item -Path 'C:\Program Files\Swift' -Recurse -Force -ErrorAction SilentlyContinue

        # Remove Haskell (GHC).
        Remove-Item -Path "$Env:LOCALAPPDATA\Programs\stack" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\ProgramData\chocolatey\lib\ghc' -Recurse -Force -ErrorAction SilentlyContinue

        # Remove Julia.
        Remove-Item -Path 'C:\hostedtoolcache\windows\Julia' -Recurse -Force -ErrorAction SilentlyContinue

        $finalSpace = (Get-PSDrive C).Free
        $freedSpace = [math]::Round(($finalSpace - $initialSpace) / 1GB, 2)
        Write-Output "Freed up approximately $freedSpace GB of disk space."
