name: Mirror branch
description: >
  Pushes the currently checked out branch to another repository.

inputs:
  push-user-name:
    description: >
      The name of the user whose credentials are used to push to the repository. Leave as default to use a PAT.
    default: PersonalAccessToken
  remote-host:
    description: The URL host of the target repository. Default is github.com.
    default: github.com
  remote-repository:
    description: The target repository path, e.g. 'Lombiq/Open-Source-Orchard-Core-Extensions'.
    required: true

runs:
  using: composite
  steps:
    - name: Push current branch to remote
      shell: pwsh
      run: |
        git remote add target 'https://${{ inputs.push-user-name }}:${{ env.PUSH_PASSWORD }}@${{ inputs.remote-host }}/${{ inputs.remote-repository }}'
        get fetch target

        $branchName = git rev-parse --abbrev-ref HEAD
        if ((git ls-remote --heads target $branchName) -eq $null -or (git log target/$branchName..$branchName) -ne $null)
        {
          git push target
        }

        git remote rm target