name: Mirror branch
description: >
  Pushes the currently checked out branch to another repository.

inputs:
  remote-host:
    description: The URL host of the target repository. Default is github.com.
    default: github.com
  remote-repository:
    description: The target repository path, e.g. 'Lombiq/Open-Source-Orchard-Core-Extensions'.
    required: true

runs:
  using: composite
  steps:
    - name: Push current branch to remote
      if: github.event.pusher.name != 'github-actions[bot]'
      shell: pwsh
      run: |
        if ('${{ inputs.remote-repository }}'.ToLower() -eq '${{ github.repository }}'.ToLower())
        {
          Write-Output 'Target repository is the current repository, nothing to do.'

          exit
        }

        # Removing extra authentication header that interferes with the PAT: https://stackoverflow.com/a/69979203
        git config --unset-all http.https://github.com/.extraheader

        # Setting credentials to be able to skip push events triggered by mirroring.
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git config user.name 'github-actions[bot]'

        git remote add target 'https://${{ env.MIRROR_TOKEN }}@${{ inputs.remote-host }}/${{ inputs.remote-repository }}'
        Write-Output 'Target remote added.'

        $branchName = git rev-parse --abbrev-ref HEAD

        git fetch target $branchName

        $pushLastExitCode = 0
        if ($LASTEXITCODE -eq 0 -and $null -eq (git log target/$branchName..$branchName))
        {
          Write-Output "'$branchName' is up-to-date on target."
        }
        else
        {
          git push target $branchName
          
          $pushLastExitCode = $LASTEXITCODE
        }

        git remote rm target
        Write-Output 'Target remote removed.'

        if ($pushLastExitCode -ne 0)
        {
          exit $pushLastExitCode
        }
