name: Lint Scripts and Styles
description: Lint JavaScript and CSS files.

inputs:
  scripts:
    required: false
    default: .:.
    description: |
      Information about the projects where JavaScript linting should occur. It's a semicolon separated list of the
      project paths. Optionally, each list item can be in the "{project path}:{glob pattern}" format as well, if you
      don't want to target all files in the project directory.
  styles:
    required: false
    default: .:**/*.css
    description: Information about the projects where CSS linting should occur. Has the same format as the "scripts" input above.
  texts:
    required: false
    default: .:**/*.{md,markdown}
    description: Information about the projects where Markdown linting should occur. Has the same format as the "scripts" input above.

runs:
  using: composite
  steps:
    - name: Set up Environment
      id: set-up-environment
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH

    - name: Execute Linting
      shell: pwsh
      run: |
        Invoke-Linter -ScriptsString '${{ inputs.scripts }}' -StylesString '${{ inputs.styles }}' -TextsString '${{ inputs.texts }}'
