name: Add Azure Application Insights Release Annotation
description: >
  Can be used to add release annotations in Azure Application Insights, to mark when a new version of an app was rolled
  out to a given environment. See https://learn.microsoft.com/en-us/azure/azure-monitor/app/annotations for details.

inputs:
  application-insights-resource-id:
    required: true
    description: >
      ID of the Application Insights resource that the release annotation should be added to. This can e.g. be looked up
      on the Azure Portal under the given AI resource's Overview page -> JSON View.
  release-name:
    required: false
    description: >
      The name to give the created release annotation. This will be visible on the Azure Portal when viewing it.
  timestamp:
    required: false
    description: >
      The timestamp to use for the release annotation. If not set then the current time will be used. This can be useful
      when using a single timestamp for multiple actions in a workflow.
  commit-sha:
    required: false
    default: ${{ github.sha }}
    description: >
      The commit SHA to include in the release annotation. If not set then the current commit SHA will be used. This is
      useful in case of a swap deployment where the code repository is different than the repository the action is
      running in.

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH

    - name: Add Azure Application Insights Release Annotation
      shell: pwsh
      env:
        # Might contain user input so should go via an env var for security.
        RELEASE_NAME: ${{ inputs.release-name }}
        AI_RESOURCE_ID: ${{ inputs.application-insights-resource-id }}
        TIMESTAMP: ${{ inputs.timestamp }}
      run: |
        $params = @{
            ApplicationInsightsResourceId = $Env:AI_RESOURCE_ID
            ReleaseName = $Env:RELEASE_NAME ? $Env:RELEASE_NAME : 'Run #${{ github.run_number }} (GitHub Actions)'
            Timestamp = $Env:TIMESTAMP
            ReleaseProperties = @{
              'Commit branch' = '${{ github.head_ref }}'
              'Commit SHA' = '${{ inputs.commit-sha }}'
              'Workflow name' = '${{ github.workflow }}'
              'Workflow run URL' = 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            }
        }
        Add-ReleaseAnnotation @params
