name: Get Changed File Names Between Commits
description: >
  Get PowerShell array of file names that changed between commits.

inputs:
  left-commit:
    required: true
    description: >
      String git commit SHA or blob to compare with right-commit for git diff.
  right-commit:
    required: true
    description: >
      String git commit SHA or blob to compare with left-commit for git diff.
  diff-filter:
    required: false
    default: ACMRT
    description: >
      String value for '--diff-filter=' flag when doing 'git diff'. See 'git diff -h'
      for more information.
outputs:
  changed-files:
    description: >
      A PowerShell array of file names from git diff between left-commit and right commit.
    value: ${{ steps.git-diff.outputs.changed-files }}
runs:
  using: composite
  steps:
    - name: Setup
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH

    - name: Git Diff
      id: git-diff
      shell: pwsh
      run: |
        $files = $(git diff --name-only --diff-filter=${{ inputs.diff-filter }} ${{ inputs.left-commit }} ${{ inputs.right-commit }})
        $output = "changed-files=@(" + $($files | Join-String -DoubleQuote -Separator ',') + ")"
        Write-Output "output=$output"
        $output >> $env:GITHUB_OUTPUT
