name: Elasticsearch Setup
description: Sets up Elasticsearch

runs:
  using: composite
  steps:
    - name: Configure sysctl limits
      shell: pwsh
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      shell: pwsh
      run: |
        # Install Docker containers using "docker compose".
        New-Item -ItemType Directory -Path Elasticsearch
        Set-Location Elasticsearch
        Copy-Item (Join-Path '${{ github.action_path }}' docker-compose.yml) .
        docker compose up --wait
        docker compose start

        # Test server status.
        function Test-Elasticsearch()
        {
          try
          {
            $result = Invoke-WebRequest http://localhost:9200/
            Write-Output $result
            return $True
          }
          catch
          {
            return $False
          }
        }

        for ($i = 0; $i -lt 10; $i += 1)
        {
          if (Test-Elasticsearch)
          {
            Write-Output ok
            break
          }
          else
          {
            Write-Output 'Wait a few seconds!'
            Start-Sleep -Seconds 3
          }
        }
