name: Elasticsearch Setup
description: Sets up Elasticsearch

runs:
  using: composite
  steps:
    - name: Configure sysctl limits
      shell: pwsh
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@a82f8694596aa6f9ce3b556c7a795ee40db626e2
      with:
        stack-version: 7.6.0
