name: Elasticsearch Setup
description: Sets up Elasticsearch

inputs:
  elasticsearch version:
    required: false
    default: latest
  host port:
    required: false
    default: 9200
  container port:
    required: false
    default: 9200
  host node port:
    required: false
    default: 9300
  node port:
    required: false
    default: 9300
  discovery type:
    required: false
    default: single-node

runs:
  using: docker
  image: Dockerfile
  steps:
    - name: install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl docker

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
