name: Elasticsearch Setup
description: Sets up Elasticsearch

runs:
  using: composite
  steps:
    - name: Configure sysctl limits
      shell: pwsh
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      shell: pwsh
      run: |
        $url = 'https://github.com/OrchardCMS/OrchardCore/raw/refs/tags/v2.2.1/src/docs/reference/modules/Elasticsearch/docker-compose.yml'
        
        New-Item -ItemType Directory -Path Elasticsearch
        Set-Location Elasticsearch
        Invoke-WebRequest $url -OutFile docker-compose.yml
        docker-compose up
