name: Elasticsearch Setup
description: Sets up Elasticsearch

runs:
  using: composite
  steps:
    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@a82f8694596aa6f9ce3b556c7a795ee40db626e2
      with:
        stack-version: 7.6.0
