name: Pull Request - Code Analysis and Unit Tests
on:
  pull_request:
    branches: [ dev ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0 on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Submodule Init
      run: |
        git submodule init && git submodule update
    - name: Static Code Analysis
      run: |
        npm install pnpm -g &&
        dotnet build Lombiq.OSOCE.sln --no-incremental -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Set up SQL Server via Docker
      run: |
        mkdir -p $PWD/docker/mssql/data
        chown $USER:docker $PWD/docker/ -R
        chmod g+w $PWD/docker/ -R
        docker pull mcr.microsoft.com/mssql/server
        docker volume create --driver local -o o=bind -o type=none -o device="$PWD/docker/mssql/data" mssql-data
        docker run --name sql2019 -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -v mssql-data:/data -p 1433:1433 -d 'mcr.microsoft.com/mssql/server:2019-latest'
        docker exec -u 0 sql2019 chown 'mssql:root' /data
        echo '{"Lombiq_Tests_UI":{"SqlServerDatabaseConfiguration":{"ConnectionStringTemplate":"Server=.;Database=LombiqUITestingToolbox_{{id}};User Id=sa;Password=yourStrong(!)Password;MultipleActiveResultSets=True;Connection Timeout=60;ConnectRetryCount=15;ConnectRetryInterval=5"},"DockerConfiguration":{"ContainerSnapshotPath":"/data","HostSnapshotPath":"~/.local/docker/mssql/data/"}}}' > ~/TestConfiguration.json
        echo LOMBIQ_SHARED_TEST_CONFIGURATION="$HOME/TestConfiguration.json" >> $GITHUB_ENV
    - name: Set up Azurite via Docker
      run: |
        docker pull mcr.microsoft.com/azure-storage/azurite &&
        docker run --name azurite -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    - name: Unit Tests
      run: |
        (dotnet sln list |
        grep '.Tests.' |
        grep -v 'Lombiq.Tests.UI.csproj' |
        grep -v 'Lombiq.Tests.csproj' |
        sed -e 's/\\/\//g' -e '$atrue' -e 's/\(.*\)/echo "::group::\1" \&\&\ndotnet test -c Release --no-restore --no-build '"'\\1'"' \&\&\necho "::endgroup::" \&\&/' |
        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
        grep SUCCESS .ui_test_result
