name: Lint Scripts, Styles, and Texts

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used.

    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'true'
      scripts:
        description: |
          Information about the projects where JavaScript linting should occur. It's a semicolon separated list of the
          project paths. Optionally, each list item can be in the "{project path}:{glob pattern}" format as well, if
          you don't want to target all files in the project directory.
        type: string
        default: .:.
      styles:
        description: Information about the projects where CSS linting should occur. Has the same format as the "scripts" input above.
        type: string
        default: .:**/*.css
      texts:
        description: Information about the projects where Markdown linting should occur. Has the same format as the "scripts" input above.
        type: string
        default: .:**/*.{md,markdown}

jobs:
  lint:
    name: Lint Scripts, Styles, and Texts
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Set up Node.js
        uses: Lombiq/GitHub-Actions/.github/actions/setup-node@dev

      - name: Lint Scripts and Styles
        uses: Lombiq/GitHub-Actions/.github/actions/asset-lint@dev
        with:
          scripts: ${{ inputs.scripts }}
          styles: ${{ inputs.styles }}
          texts: ${{ inputs.texts }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
