name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow-larger-runners:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"ubuntu-latest-8core\"]"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-enable-nuget-caching: "true"
      build-enable-npm-caching: "true"
