name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  push:
    branches:
      - issue/INFRA-111

jobs:
  test-workflow-webhook:
    runs-on: "[\"self-hosted\"]"
    name: Test
    timeout-minutes: 10
    steps:
      - name: Who am I?
        shell: pwsh
        run: whoami
