name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-dotnet.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      timeout-minutes: 30
      build-verbosity: normal
