name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners0:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)0
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['windows-2022-8core', 'gitrunners-windows-2022-x64-8vcpu']"
      timeout-minutes: 180
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"
      cancel-workflow-on-failure: "false"

  build-and-test-larger-runners1:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)1
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['windows-2022-8core', 'gitrunners-windows-2022-x64-8vcpu']"
      timeout-minutes: 180
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"
      cancel-workflow-on-failure: "false"

  build-and-test-larger-runners2:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)2
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['windows-2022-8core', 'gitrunners-windows-2022-x64-8vcpu']"
      timeout-minutes: 180
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"
      cancel-workflow-on-failure: "false"

  build-and-test-larger-runners3:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)3
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['windows-2022-8core', 'gitrunners-windows-2022-x64-8vcpu']"
      timeout-minutes: 180
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"
      cancel-workflow-on-failure: "false"

  build-and-test-larger-runners4:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)4
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['windows-2022-8core', 'gitrunners-windows-2022-x64-8vcpu']"
      timeout-minutes: 180
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"
      cancel-workflow-on-failure: "false"
