name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow0:
    name: Build and Test - root solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest-4core\", \"windows-latest-8core\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0
      build-enable-npm-caching: "true"

  call-build-and-test-workflow1:
    name: Build and Test - root solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest-4core\", \"windows-latest-8core\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0
      build-enable-npm-caching: "true"

  call-build-and-test-workflow2:
    name: Build and Test - root solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest-4core\", \"windows-latest-8core\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0
      build-enable-npm-caching: "true"

  call-build-and-test-workflow3:
    name: Build and Test - root solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest-4core\", \"windows-latest-8core\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0
      build-enable-npm-caching: "true"
