name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners-dev0:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-dev0:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-dev1:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-dev1:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-dev2:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-dev2:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-dev3:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-dev3:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-dev4:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-dev4:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-maxCpuCount0:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test maxCpuCount - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-maxCpuCount0:
    name: Build and Test maxCpuCount - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-maxCpuCount1:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test maxCpuCount - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-maxCpuCount1:
    name: Build and Test maxCpuCount - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-maxCpuCount2:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test maxCpuCount - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-maxCpuCount2:
    name: Build and Test maxCpuCount - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-maxCpuCount3:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test maxCpuCount - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-maxCpuCount3:
    name: Build and Test maxCpuCount - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"

  build-and-test-larger-runners-maxCpuCount4:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test maxCpuCount - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['gitrunners-ubuntu-2204-x64-4vcpu', 'windows-2022-8core']"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  build-and-test-nuget-test-maxCpuCount4:
    name: Build and Test maxCpuCount - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/COLI-870
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      build-directory: NuGetTest
      timeout-minutes: 20
      blame-hang-timeout: "5m"
