name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow-nuget-test00:
    name: Build and Test - NuGetTest solution 00
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 0

  call-build-and-test-workflow-nuget-test01:
    name: Build and Test - NuGetTest solution 01
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 0

  call-build-and-test-workflow-nuget-test02:
    name: Build and Test - NuGetTest solution 02
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 0

  call-build-and-test-workflow-nuget-test20:
    name: Build and Test - NuGetTest solution 20
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 2

  call-build-and-test-workflow-nuget-test21:
    name: Build and Test - NuGetTest solution 21
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 2

  call-build-and-test-workflow-nuget-test22:
    name: Build and Test - NuGetTest solution 22
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 2

  call-build-and-test-workflow-nuget-test40:
    name: Build and Test - NuGetTest solution 40
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 4

  call-build-and-test-workflow-nuget-test41:
    name: Build and Test - NuGetTest solution 41
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 4

  call-build-and-test-workflow-nuget-test42:
    name: Build and Test - NuGetTest solution 42
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
      ui-test-parallelism: 4
