name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/NEST-314
    with: 
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directories: "[\".\", \"NuGetTest\"]"
