name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  test-workflow-webhook:
    runs-on: "[\"ubuntu-latest\"]"
    name: Test
    timeout-minutes: 1
    steps:
      - name: Who am I?
        shell: pwsh
        run: whoami
