name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow-on-self-hosted-runner:
    name: Build and Test - root solution (self-hosted runner)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/INFRA-111
    with:
      machine-types: "[\"self-hosted\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0
