name: Pull Request - Build and Test
on: pull_request
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Submodule Init
      run: |
        git submodule init && git submodule update
    - name: Build and Static Code Analysis
      run: |
        npm install pnpm -g
        dotnet build src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj --configuration Release
        dotnet build Lombiq.OSOCE.sln --configuration Release -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzersDuringBuild=true -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
    - name: Set up SQL Server via Docker
      run: |
        docker pull mcr.microsoft.com/mssql/server
        docker run --name sql2019 -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d 'mcr.microsoft.com/mssql/server:2019-latest'
        docker exec -u 0 sql2019 bash -c 'mkdir /data; chmod 777 /data -R; chown mssql:root /data'
    - name: Set up Azurite via Docker
      run: |
        docker pull mcr.microsoft.com/azure-storage/azurite &&
        docker run --name azurite -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    - name: Tests
      run: |
        export LOMBIQ_SHARED_TEST_CONFIGURATION="$PWD/.github/TestConfig.json"
        (dotnet sln list |
        grep '.Tests.' |
        grep -v 'Lombiq.Tests.UI.csproj' |
        grep -v 'Lombiq.Tests.csproj' |
        sed -e 's/\\/\//g' -e '$atrue' -e 's/\(.*\)/echo "::group::\1" \&\&\ndotnet test -c Release --no-restore --no-build '"'\\1'"' \&\&\necho "::endgroup::" \&\&/' |
        bash && (echo SUCCESS > .ui_test_result) || (echo FAIL > .ui_test_result)) | grep -v '^Connection refused \[::ffff:127.0.0.1\]';
        grep SUCCESS .ui_test_result
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
          name: ui-test-failure
          path: |
              test/OrchardCore.Tests.UI/bin/Release/*/FailureDumps
