name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and Test
    strategy:
      matrix:
        directory: ['.']
        os: [windows-latest]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
      with:
        path: o
        submodules: 'recursive'

    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Build and Static Code Analysis
      working-directory: ${{ matrix.directory }}
      run: |
        corepack enable

        if (Test-Path src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj)
        {
            dotnet build src/Utilities/Lombiq.Gulp.Extensions/Lombiq.Gulp.Extensions.csproj --configuration Release
        }

        $buildSwitches = @(
            '--configuration',
            'Release',
            '-warnaserror',
            '-p:TreatWarningsAsErrors=true',
            '-p:RunAnalyzersDuringBuild=true',
            '-nologo',
            '-consoleLoggerParameters:NoSummary',
            '-verbosity:minimal'
        )

        dotnet build (Get-ChildItem *.sln).FullName @buildSwitches
