name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow:
    name: Build and Test - root solution
    runs-on: TC-mod
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test:
    name: Build and Test - NuGetTest solution
    runs-on: TC-mod
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      build-directory: NuGetTest
      timeout-minutes: 30
