name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners:
    strategy:
      matrix:
        run-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # Runs the job 10 times.
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04']"
      timeout-minutes: 20
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

  add-windows-build-warning-label:
    name: Add Windows Build Warning Label
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    needs: [build-and-test-larger-runners]
    steps:
    - name: Add Windows Build Warning Label
      # v2.0.0
      uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835
      with:
        # The token is necessary to be able to add the label even if the workflow is triggered by a pull request coming
        # from a fork.
        token: ${{ secrets.LOMBIQBOT_GITHUB_PERSONAL_ACCESS_TOKEN }}
        labels: requires-windows-build
        type: add
