name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-larger-runners:
    if: github.ref_name != github.event.repository.default_branch
    name: Build and Test - root solution (larger runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-84-final
    with:
      machine-types: "[\"windows-latest-16core\"]"
      timeout-minutes: 30
      set-up-sql-server: "true"
      set-up-azurite: "true"
      ui-test-parallelism: 0
      build-create-binary-log: "true"
      build-verbosity: normal

  build-and-test-standard-runners:
    # Since dev builds are not awaited by anyone, they can run on the slower free runners.
    if: github.ref_name == github.event.repository.default_branch
    name: Build and Test - root solution (standard runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      timeout-minutes: 60
      set-up-sql-server: "true"
      set-up-azurite: "true"

  build-and-test-nuget-test:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-84-final
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 20
      # This is a test configuration for https://github.com/Lombiq/UI-Testing-Toolbox/issues/228.
      xunit-max-parallel-threads: -1
