name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-and-test-workflow-nuget-test0:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test1:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test2:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test3:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test4:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test5:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test6:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test7:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test8:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test9:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test10:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test11:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test12:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test13:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test14:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test15:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test16:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test17:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test18:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60

  call-build-and-test-workflow-nuget-test19:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/OSOE-464
    with:
      machine-types: "[\"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 60
