name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and Test
    strategy:
      matrix:
        directory: ['.', 'NuGetTest']
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 60
    steps:
      - uses: Lombiq/GitHub-Actions/.github/actions/build-and-test-orchard-core@issue/NEST-314
        with:
          os: ${{ matrix.os }}
          build-directory: ${{ matrix.directory }}
