name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  call-build-workflow:
    name: Build and Test - root solution
    uses: Lombiq/Open-Source-Orchard-Core-Extensions/.github/workflows/build-dotnet-with-pnpm.yml@issue/OSOE-125
    with:
      machine-types: "[\"ubuntu-latest-4core\", \"windows-latest-8core\"]"
      timeout-minutes: 60
      ui-test-parallelism: 0

  call-build-workflow-nuget-test:
    name: Build and Test - NuGetTest solution
    uses: Lombiq/Open-Source-Orchard-Core-Extensions/.github/workflows/build-dotnet-with-pnpm.yml@issue/OSOE-125
    with:
      machine-types: "[\"ubuntu-latest\", \"windows-latest\"]"
      build-directory: NuGetTest
      timeout-minutes: 30
