name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  workflow_dispatch:

jobs:
  call-build-and-test-workflow:
    name: Build and Test - root solution
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "[\"self-hosted\"]"
      timeout-minutes: 60
