name: Build and Test

# Runs for PRs opened for any branch, and pushes to the dev branch.
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build-and-test-standard-runners:
    # Since dev builds are not awaited by anyone, they can run on the slower free runners.
    name: Build and Test - root solution (standard runners)
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@dev
    with:
      machine-types: "['ubuntu-22.04', 'windows-2022']"
      timeout-minutes: 60
      set-up-sql-server: "true"
      set-up-azurite: "true"
      build-create-binary-log: "true"
      blame-hang-timeout: "5m"

