name: Mirror branches from a repository to another

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      SOURCE_REPOSITORY_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checking out the source repository. Pass in a GitHub personal access token if
          authenticated submodules are used.

      DESTINATION_REPOSITORY_TOKEN:
        required: true
        description: The PAT to authenticate with on the destination repository.

    inputs:
      machine-type:
        type: string
        default: ubuntu-24.04
        description: The type of machine to run the workflow on.
      timeout-minutes:
        type: number
        default: 5
        description: Configuration for the timeout-minutes parameter of the workflow.
      source-repository:
        description: >
          The repository to mirror branches from, e.g. 'Lombiq/GitHub-Actions'. Default value is the current repository.
        type: string
        default: ${{ github.repository }}
      destination-repository:
        description: The destination repository path, e.g. 'Lombiq/GitHub-Actions'.
        type: string
        required: true
      branch-names:
        description: >
          A space-separated list of branch names to push to the destination repository. Use this parameter when the
          names of the branches that are outdated on the destination are known and doesn't need to be checked, e.g. when
          the workflow is triggered by the push event in the source repository. This parameter takes precedence over
          'branch-names' when not empty.
        type: string
        default: ''
      branch-regex:
        description: >
          A regex to match the branches of the source repository. Matched branches will be checked against the
          destination repository to determine if the head commit hashes differ to prevent unnecessary push operations.
          Default value matches any branch.
        type: string
        default: '.+'

jobs:
  mirror:
    runs-on: ${{ inputs.machine-type }}
    name: Checkout and push to destination
    if: inputs.destination-repository != inputs.source-repository
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Push to destination
        uses: Lombiq/GitHub-Actions/.github/actions/mirror-branches@issue/OSOE-737
        env:
          SOURCE_REPOSITORY_TOKEN: ${{ secrets.SOURCE_REPOSITORY_TOKEN }}
          DESTINATION_REPOSITORY_TOKEN: ${{ secrets.DESTINATION_REPOSITORY_TOKEN }}
        with:
          source-repository: ${{ inputs.source-repository }}
          destination-repository: ${{ inputs.destination-repository }}
          branch-names: ${{ inputs.branch-names }}
          branch-regex: ${{ inputs.branch-regex }}
