name: Open Pull Request

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used.

    inputs:
      source-branch:
        type: string
        required: false
        default: ${{ github.head_ref }}
        description: The name of the source branch for the pull request.
      target-branch:
        type: string
        required: false
        default: ${{ github.event.repository.default_branch }}
        description: The name of the target branch for the pull request.
      pull-request-body:
        type: string
        required: false
        default: ''
        description: The body text for the pull request.

jobs:
  lint:
    name: Open Pull Request
    runs-on: ubuntu-24.04
    steps:
      - name: Set Checkout Token
        uses: Lombiq/GitHub-Actions/.github/actions/set-checkout-token@issue/OSOE-1294
        with:
          checkout-token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@issue/OSOE-1294
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Open Pull Request
        uses: Lombiq/GitHub-Actions/.github/actions/open-pull-request@issue/OSOE-1294
        env:
          GITHUB_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        with:
          source-branch: ${{ inputs.source-branch }}
          target-branch: ${{ inputs.target-branch }}
          pull-request-body: ${{ inputs.pull-request-body }}
