name: Test Workflow Actions

on:
  pull_request:
  push:
    branches: [dev]

permissions:
  contents: read
  actions: read

jobs:
  test:
    name: Test Workflow Actions
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Collect Workflow Telemetry
        uses: ./.github/actions/workflow-telemetry
        with:
          metric_frequency: '1'

      - name: Test Label Updates
        shell: pwsh
        run: ./.github/actions/add-remove-label/Test-UpdateLabels.ps1

      - name: Generate Metrics
        shell: pwsh
        run: |
          $values = 1..100000 | ForEach-Object { [Math]::Sqrt($_) }
          Write-Output "Calculated $($values.Count) values."
          Start-Sleep -Seconds 5
