# Workflows triggered by pull requests from forked repositories are executed with read-only token
# and therefore can't create check runs. To workaround this security restriction, it's required to
# use two separate workflows

name: Report

on:
  workflow_run:
    workflows: [Build and Test]
    types:
      - completed
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: phoenix-actions/test-reporting@v8
        id: test-report
        with:
          artifact: test-results
          name: Test Results
          path: '**/*.trx'
          reporter: dotnet-trx
