name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build and Test' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    name: Report
    steps:
      - uses: phoenix-actions/test-reporting@v8
        id: test-report
        with:
          artifact: test-results
          name: XUnit Tests
          path: '**/TestResults/*.trx'
          reporter: 'dotnet-trx'
