name: Validate NuGet Publish

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used.
      ENVIRONMENT_VARIABLES_JSON:
        required: false
        description: >
          A JSON string containing key-value pairs of environment variables to be set. You can use this to pass in
          arbitrary environment variables that can be used to e.g. customize the build or test execution. Example:
          ENVIRONMENT_VARIABLES_JSON: |
            {
              "MY_ENV_VAR": "value of environment variable",
              "MY_ENV_VAR2": "value of environment variable"
            }

    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'false'
      verbosity:
        type: string
        default: minimal
        description: The logging verbosity type used by the `dotnet` command.
      dotnet-version:
        type: string
        default: 8.0.319
        description: Version of the .NET SDK to set up.
      node-version:
        type: string
        default: 24.10.0
        description: >
          The Node.js version. Can be a specific version number or other notations, see the documentation of
          https://github.com/actions/setup-node.
      node-package-manager-cache:
        type: string
        default: 'false'
        description: >
          Set to true to enable automatic caching based on the package manager field in package.json. By default,
          caching is disabled for this workflow (which is different from the underlying action's default behavior), to
          improve stability and backwards compatibility.
      timeout-minutes:
        type: number
        default: 15
        description: Configuration for the timeout-minutes parameter of the workflow. 360 is GitHub's default.
      enable-corepack:
        type: string
        default: 'false'
        description: Indicates whether to enable Node.js corepack before the build.
      dotnet-pack-ignore-warning:
        type: string
        default: ''
        description: >
          Additional warning codes for the `-p:NoWarn=` argument of `dotnet pack`. The items can be separated by any
          whitespace, including newlines.
      dotnet-pack-include-symbols:
        type: string
        default: 'true'
        description: If set to "true", a symbol package will be created together with the NuGet package.
      nuget-artifact-retention-days:
        type: string
        default: '1'
        description: >
          Duration in days after which the artifact of the NuGet package publishing (if any) will expire. See
          https://github.com/actions/upload-artifact#retention-period for more details.
      add-source-link-package:
        type: string
        default: 'true'
        description: If set to "true", the Microsoft.SourceLink.GitHub NuGet package is added to the projects.
      mark-breaking-changes:
        type: string
        default: 'true'
        description: |
          When set to 'true', failed package validation against the baseline will mark the pull request with a title
          suffix, a breaking-changes label, and a guidance comment.

jobs:
  validate-nuget-publish:
    name: Validate NuGet Publish
    uses: Lombiq/GitHub-Actions/.github/workflows/publish-nuget.yml@renovate/all-dependencies
    with:
      cancel-workflow-on-failure: ${{ inputs.cancel-workflow-on-failure }}
      verbosity: ${{ inputs.verbosity }}
      dotnet-version: ${{ inputs.dotnet-version }}
      node-version: ${{ inputs.node-version }}
      node-package-manager-cache: ${{ inputs.node-package-manager-cache }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
      enable-corepack: ${{ inputs.enable-corepack }}
      # NoWarn on NU5104 to not have warnings for prerelease dependencies for non-prerelease versions (see
      # https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104) since those are fine during just
      # the validation stage (they should only be avoided for actual non-prerelease publishes).
      dotnet-pack-ignore-warning: ${{ inputs.dotnet-pack-ignore-warning }}%3BNU5104
      dotnet-pack-include-symbols: ${{ inputs.dotnet-pack-include-symbols }}
      publish-version: USE_NEXT_PATCH_VERSION
      nuget-artifact-retention-days: ${{ inputs.nuget-artifact-retention-days }}
      add-source-link-package: ${{ inputs.add-source-link-package }}
      dry-run: true
      mark-breaking-changes: ${{ inputs.mark-breaking-changes }}
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      API_KEY: not needed
      ENVIRONMENT_VARIABLES_JSON: ${{ secrets.ENVIRONMENT_VARIABLES_JSON }}
