name: Print summary of important configuration
description: Contains .NET, Node.js, and pnpm versions, among others

runs:
  using: composite
  steps:
    - name: Write configuration to summary
      shell: pwsh
      run: |
        $toolVersions = @"
          | Tool | Version |
          | :--- | ------: |
          | dotnet | $(dotnet --version) |
          | dotnetSdks | $(dotnet --list-sdks) |
          | node | $(node -v) |
          | pnpm | $(pnpm -v) |
        "@
        $toolVersions >> $env:GITHUB_STEP_SUMMARY
